### ISSUE TITLE
Applying Reinforcement Learning

### ISSUE THREAD

**Issue by miguel-arrf** [semitable/robotic-warehouse#12]
Hi!

Does anyone have any documentation or tutorial on how to apply Multi-Agent Reinforcement Learning for this enviroment?

I'm having an hard time finding any good resources on how to use rlib or stable-baslines (or any other framework) for **any** openAI Gym environment with multi-agents.

(PS: I understand that this is not an issue, but I didn't know any better place for this :p).

Thank you!

**Comment by semitable** [comment]
Hi!

Have you seen the E-PyMARL codebase? It can be found here: https://github.com/uoe-agents/epymarl
and it implements many interesting MARL algorithms. There are instructions on how to use it with RWARE.

**Comment by miguel-arrf** [comment]
Hi!

Oh, nice! I wasn't aware of that repository. I'm going to have a look!

Thank you so much! 🤩
