### ISSUE TITLE
AttributeError: `Warehouse` object has no attribute `shelfs`

### ISSUE THREAD

**Issue by sym-lening** [semitable/robotic-warehouse#18]
![image](https://user-images.githubusercontent.com/123997581/216085088-65eafe48-af35-4371-a270-ada570d97db9.png)
I am getting this error.

**Comment by aryu99** [comment]
@sym-lening were you able to fix this?

**Comment by sym-lening** [comment]
No

**Comment by aryu99** [comment]
@sym-lening call `env.reset()` before rendering. The `shelf` attribute is initialized inside `reset`.

```
env = gym.make("rware-tiny-2ag-v1", sensor_range=9, request_queue_size=2, layout=layout)
env.reset()
env.render()
time.sleep(5)
```

**Comment by sym-lening** [comment]
it works.
