### ISSUE TITLE
Can I unload at a shelf instead of the Goal location?

### ISSUE THREAD

**Issue by aryu99** [semitable/robotic-warehouse#19]
Pretty much the title.

**Comment by semitable** [comment]
Agents can "unload" at a shelf location (not on the corridors). That means they'll leave the shelf down.

Not sure what you mean "instead of the Goal location". The goal location is just an in-between step, and the agents don't unload there.

**Comment by aryu99** [comment]
By Goal position, I meant 'G' (In the example custom string-based layout), the location at which the agents are rewarded. Is it possible for the agents to instead unload at an empty shelf and not the 'G' Goal location?

**Comment by semitable** [comment]
But they don't unload at the goal location; they merely visit it and then return the shelf to an empty spot. The load/unload action is only used in empty shelf locations (not goal locations!)

**Comment by aryu99** [comment]
I see. I was confusing loading/unloading of the shelfs, against the unloading of the **_contents_** of the shelfs at the goal location.

Thanks for the clarification!
