### ISSUE TITLE
Check for whether agent is unloading shelf at a location where another shelf is already present.

### ISSUE THREAD

**Issue by aryu99** [semitable/robotic-warehouse#21]
Hi. I am working on a project where I need to modify some of your source code. While going through it, I noticed that you do a check when you toggle load for unloading, to ensure that it does not unload on a highway. From what I can understand a highway is defined as any place not instantiated as a shelf location. 

However, I do not see a check for whether you are trying to unload at a location where a shelf is already present. 
<img width="313" alt="image" src="https://user-images.githubusercontent.com/40424189/229593292-24f05462-ca89-4ae3-a29e-09fe697a5d48.png">

Is that check not done? Is it possible to unload at a non-empty shelf location? Or do you do this check somewhere or maybe define shelf locations already containing a shelf as a highway?

Thank you!

**Comment by aryu99** [comment]
Essentially, where do you check whether the unload shelf action is being performed at a place already occupied by a shelf or not?

**Comment by aryu99** [comment]
Sorry, looking deeper into the code, I think I understand it now. Thanks.

**Comment by semitable** [comment]
Hi @aryu99. I think an agent can never move into a location containing a shelf while carrying a shelf (this is handled by the collision code) :)
