### ISSUE TITLE
Bugs caused by gym version changes

### ISSUE THREAD

**Issue by wwxFromTju** [semitable/robotic-warehouse#7]
Hi,

Great environment, good job!

But it is worth pointing out that due to the change of the gym version to 0.20 or more, the calculation of the number of dimensions of MultiDiscrete has changed. This also leads to different observation dim under different gym versions, and makes the way of writing information in the function _make_obs wrong.

eg：https://github.com/semitable/robotic-warehouse/blob/be626e41898d91ff4359d215960ab9b6d9943d27/rware/warehouse.py#L384

Should be modified to something like：https://github.com/semitable/robotic-warehouse/blob/be626e41898d91ff4359d215960ab9b6d9943d27/rware/warehouse.py#L397-L399

**Comment by semitable** [comment]
Hi @wwxFromTju ,

Thanks for the issue report. I recently noticed this problem and raised issue #4 and pushed commit #be626e4 which changes the multi discrete space and pins gym version to >=0.20. 

Is this a duplicate of this issue or you have noticed a problem in the newest version as well?

Thanks

**Comment by wwxFromTju** [comment]
hey, we used the previous version of the code and it looks like the latest version of the code fixes the problem (please note, I didn't try the latest version of the code).

Very good environment, looking forward to your new work and cooperation.

**Comment by wwxFromTju** [comment]
I reviewed the problem and found that the code of PyPi is still an old version, please pay attention to update the code in PyPi

**Comment by semitable** [comment]
Thanks for noticing @wwxFromTju 
The newest version has been uploaded to PyPi now.
