### ISSUE TITLE
creating the environment 

### ISSUE THREAD

**Issue by DeenaAbusham** [semitable/robotic-warehouse#9]
when I try to execute this line:
 env.render()
I get this error:
[/usr/local/lib/python3.7/dist-packages/pyglet/canvas/xlib.py](https://localhost:8080/#) in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"

**Comment by semitable** [comment]
This error is generated outside of our code. I think the rendering library is not finding a screen. Are you running this on a server or locally? If you are running it on a server I would suggest disabling rendering.
